### ISSUE TITLE
оишбка

### ISSUE THREAD

**Issue by Merrow1337** [vericuarab/lol#1]
https://imgur.com/a/oyPB6Sn
переместил все установленные файлы в отдельную папку,выбрал игру в инжекторе,выбрал файл,нажал инжект,выходит эта ошибка. Что делать?

**Comment by vericuarab** [comment]
hello there, this file has been patched as a result of the game reciving updates and getting an anti cheat. I will try to find a fix but till than it's patched. Thanck you for anouncing me that. And in future if you have an error i would like if you will be able to type this in english. Kind regards Vericuarab

**Comment by vericuarab** [comment]
Patched
